// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlkiguhcafvkccinwvbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indsa2lndWhjYWZ2a2NjaW53dmJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNTgyOTQsImV4cCI6MjA2MjgzNDI5NH0.MvTtquF_A0DMp8hxK3-stqIQIGf2JhdiZ13fPmSrrZo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);